name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . 
          push: true
          tags: ghcr.io/${{ secrets.REGISTRY_USERNAME }}/zeniushub_admin_frontend_dev:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker login ghcr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_TOKEN }}
            sudo docker pull ghcr.io/${{ secrets.REGISTRY_USERNAME }}/zeniushub_admin_frontend_dev:latest

            # Find the container running on port 3002
            container_id=$(sudo docker ps -q -f "publish=3002")

            # Stop and remove the container if it exists
            if [ ! -z "$container_id" ]; then
              sudo docker stop $container_id
              sudo docker rm $container_id
            fi

            # Run the new container
            sudo docker run -d -p 3002:3002 ghcr.io/${{ secrets.REGISTRY_USERNAME }}/zeniushub_admin_frontend_dev:latest
